import { Box, Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Feed from "../components/Feed";

const Home: NextPage = () => {
  return (
    <div className={""}>
      <Head>
        <title>Youtube clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box
        sx={{
          background: "#000",
        }}>
        <Feed />
      </Box>
    </div>
  );
};

export default Home;
